CREATE TABLE JEFE_DE_TURNO (
  DNI VARCHAR2(20) NOT NULL,
  CUANTOS NUMBER,
  ANTIGUEDAD NUMBER,
  CONSTRAINT PK_JEFE_DE_TURNO PRIMARY KEY (DNI)
);


CREATE TABLE PERSONAL (
  TIP_PERSONAL NUMBER NOT NULL,
  PCP VARCHAR2(50) NOT NULL,
  NOMBRE VARCHAR2(50),
  APELLIDO VARCHAR2(50),
  DNI_JEFE_DE_TURNO VARCHAR2(20) NOT NULL,
  CONSTRAINT UK_PERSONAL UNIQUE(PCP),
  CONSTRAINT PK_PERSONAL PRIMARY KEY (TIP_PERSONAL),
  CONSTRAINT FK_PERSONAL_JEFE_DE_TURNO FOREIGN KEY (DNI_JEFE_DE_TURNO) REFERENCES JEFE_DE_TURNO (DNI)
);

CREATE TABLE CAPATACES (
  DNI_CAPATAZ VARCHAR2(20) NOT NULL,
  TIP_CAPATAZ NUMBER NOT NULL,
  CONSTRAINT PK_CAPATACES PRIMARY KEY (TIP_CAPATAZ),
  CONSTRAINT FK_CAPATACES_PERSONAL FOREIGN KEY (TIP_CAPATAZ) REFERENCES PERSONAL (TIP_PERSONAL)
);




CREATE TABLE INCIDENCIAS (
  N_EXPEDIENTE VARCHAR2(20),
  N_INCIDENCIA NUMBER NOT NULL,
  CONSTRAINT PK_INCIDENCIAS PRIMARY KEY (N_INCIDENCIA)
);

CREATE TABLE ABRIR (
  HORA VARCHAR2(20),
  DANOS VARCHAR2(100),
  NOM_RESP VARCHAR2(50),
  QUIEN VARCHAR2(50),
  TIP_PERSONAL NUMBER NOT NULL,
  N_INCIDENCIA NUMBER NOT NULL,
  CONSTRAINT PK_ABRIR PRIMARY KEY(N_INCIDENCIA,TIP_PERSONAL),
  CONSTRAINT ABRIR_TIP_PERSONAL FOREIGN KEY(TIP_PERSONAL) REFERENCES PERSONAL (TIP_PERSONAL),
  CONSTRAINT ABRIR_N_INCIDENCIA FOREIGN KEY(N_INCIDENCIA) REFERENCES INCIDENCIAS (N_INCIDENCIA)
);


CREATE TABLE CAPATAZ_PISTA (
  TIP_CAPATAZPISTA NUMBER NOT NULL,
  EMISORA VARCHAR2(50),
  FURGONETA VARCHAR2(50),
  TIPO_FURGO VARCHAR2(50),
  CONSTRAINT PK_CAPATAZ_PISTA PRIMARY KEY (TIP_CAPATAZPISTA),
  CONSTRAINT CAPATAZ_PISTA_TIP_CAPATAZPISTA FOREIGN KEY (TIP_CAPATAZPISTA) REFERENCES CAPATACES (TIP_CAPATAZ)
);

CREATE TABLE OPERARIOS (
  TIP_PERSONAL NUMBER NOT NULL,
  CONTRATO VARCHAR2(20),
  CONSTRAINT PK_OPERARIOS PRIMARY KEY (TIP_PERSONAL),
  CONSTRAINT FK_OPERARIOS_TIP_PERSONAL FOREIGN KEY (TIP_PERSONAL) REFERENCES PERSONAL (TIP_PERSONAL)
);

CREATE TABLE CAPATAZ_HIPODROMO (
  TURNO VARCHAR2(20),
  TIP_CAPATAZHIPODROMO NUMBER NOT NULL,
  CONSTRAINT PK_CAPATAZ_HIPODROMO PRIMARY KEY (TIP_CAPATAZHIPODROMO),
  CONSTRAINT FK_CAPATAZ_HIPODROMO_TIP_CAPATAZ FOREIGN KEY (TIP_CAPATAZHIPODROMO) REFERENCES CAPATACES (TIP_CAPATAZ)
);



CREATE TABLE OPERARIOS_HIPODROMO (
  PAUSA VARCHAR2(20),
  DESTINOS_SALIDA VARCHAR2(50),
  TIP_OPERARIOHIPODROMO NUMBER NOT NULL,
  TIP_CAPATAZHIPODROMO NUMBER NOT NULL,
  CONSTRAINT PK_OPERARIOS_HIPODROMO PRIMARY KEY (TIP_OPERARIOHIPODROMO, TIP_CAPATAZHIPODROMO),
  CONSTRAINT FK_OPERARIOS_HIPODROMO_CAPATAZ_HIPODROMO FOREIGN KEY (TIP_CAPATAZHIPODROMO) REFERENCES CAPATAZ_HIPODROMO (TIP_CAPATAZHIPODROMO)
);

CREATE TABLE GRUPO (
CUANTOS NUMBER,
VUELOS VARCHAR2(20),
TIP_GRUPO NUMBER NOT NULL,
TIP_CAPATAZPISTA NUMBER NOT NULL,
CONSTRAINT PK_GRUPO PRIMARY KEY (TIP_GRUPO),
CONSTRAINT FK_GRUPO_CAPATAZ_PISTA FOREIGN KEY (TIP_CAPATAZPISTA) REFERENCES CAPATAZ_PISTA (TIP_CAPATAZPISTA),
CONSTRAINT FK_GRUPO_OPERARIOS FOREIGN KEY (TIP_GRUPO) REFERENCES OPERARIOS (TIP_PERSONAL)
);


CREATE TABLE OPERARIO_PISTA (
N_BODEGAS NUMBER,
CINTA VARCHAR2(50),
MATRICULAS VARCHAR2(50),
TIP_GRUPOPISTA NUMBER NOT NULL,
CONSTRAINT PK_OPERARIO_PISTA PRIMARY KEY (TIP_GRUPOPISTA),
CONSTRAINT FK_OPERARIO_PISTA_GRUPO FOREIGN KEY (TIP_GRUPOPISTA) REFERENCES GRUPO (TIP_GRUPO)
);

CREATE TABLE OPERARIO_ENTREGAS (
  N_TRACTOR VARCHAR2(20),
  TURNO VARCHAR2(20),
  PAUSA VARCHAR2(20),
  MATRICULA VARCHAR2(20),
  TIP_OPERARIOENTREGAS NUMBER NOT NULL,
  CONSTRAINT PK_OPERARIO_ENTREGAS PRIMARY KEY (TIP_OPERARIOENTREGAS),
  CONSTRAINT FK_OPERARIO_ENTREGAS_OPERARIOS FOREIGN KEY (TIP_OPERARIOENTREGAS) REFERENCES OPERARIOS (TIP_PERSONAL)
);

CREATE TABLE EQUIPAJES (
  PESO NUMBER,
  BN VARCHAR2(20) NOT NULL,
  NOMBRE VARCHAR2(50),
  TOTAL NUMBER,
  CONSTRAINT PK_EQUIPAJES PRIMARY KEY (BN)
);


CREATE TABLE EQUIPAJE_ESPECIAL (
  TAMAÑO VARCHAR2(20),
  CONTENIDO VARCHAR2(100),
  PESO NUMBER,
  BN VARCHAR2(20) NOT NULL,
  CONSTRAINT PK_EQUIPAJE_ESPECIAL PRIMARY KEY (BN),
  CONSTRAINT FK_EQUIPAJE_ESPECIAL_EQUIPAJES FOREIGN KEY (BN) REFERENCES EQUIPAJES (BN)
);



CREATE TABLE COORDINAR_OPERARIOS_ENTREGAS (
  TIP_OPERARIOENTREGAS1 NUMBER NOT NULL,
  TIP_OPERARIOENTREGAS2 NUMBER NOT NULL,
  CONSTRAINT PK_COORDINAR_OPERARIOS_ENTREGAS PRIMARY KEY (TIP_OPERARIOENTREGAS1, TIP_OPERARIOENTREGAS2),
  CONSTRAINT FK_COORDINAR_OPERARIOS_ENTREGAS_OPERARIO1 FOREIGN KEY (TIP_OPERARIOENTREGAS1) REFERENCES OPERARIO_ENTREGAS (TIP_OPERARIOENTREGAS),
  CONSTRAINT FK_COORDINAR_OPERARIOS_ENTREGAS_OPERARIO2 FOREIGN KEY (TIP_OPERARIOENTREGAS2) REFERENCES OPERARIO_ENTREGAS (TIP_OPERARIOENTREGAS)
);


CREATE TABLE CONDUCTOR_JARDINERA (
  TIP_CONDUCTOR NUMBER NOT NULL,
  EXPERIENCIA NUMBER,
  EMISORA VARCHAR2(50),
  CONSTRAINT PK_CONDUCTOR_JARDINERA PRIMARY KEY (TIP_CONDUCTOR),
  CONSTRAINT FK_CONDUCTOR_JARDINERA_GRUPO FOREIGN KEY (TIP_CONDUCTOR) REFERENCES GRUPO(TIP_GRUPO)
);

CREATE TABLE CARRETERO(
    PERMISO NUMBER,
    N_TRACTOR VARCHAR2(20),
    MATRICULA VARCHAR2(20),
    PERMISO_CONDUCCION VARCHAR2(20),
    TIP_CARRETERO NUMBER NOT NULL,
    AYUDA_CARRETERO NUMBER,
    CONSTRAINT PK_CARRETERO PRIMARY KEY (TIP_CARRETERO),
    CONSTRAINT FK_CARRETERO_GRUPO FOREIGN KEY (TIP_CARRETERO) REFERENCES GRUPO(TIP_GRUPO),
    CONSTRAINT FK_CARRETERO_AYUDA FOREIGN KEY (AYUDA_CARRETERO) REFERENCES CARRETERO(TIP_CARRETERO)
);


CREATE TABLE ENTREGAR (
  HORA_FINAL NUMBER,
  HORA_INICIO NUMBER,
  MUELLE VARCHAR2(50),
  BN VARCHAR2(20) NOT NULL,
  TIP_OPERARIOENTREGAS NUMBER NOT NULL,
  TIP_CARRETERO NUMBER NOT NULL,
  CONSTRAINT PK_ENTREGAR PRIMARY KEY (BN, TIP_OPERARIOENTREGAS, TIP_CARRETERO),
  CONSTRAINT FK_ENTREGAR_CARRETERO FOREIGN KEY (TIP_CARRETERO) REFERENCES CARRETERO(TIP_CARRETERO),
  CONSTRAINT FK_ENTREGAR_OPERARIO_ENTREGAS FOREIGN KEY (TIP_OPERARIOENTREGAS) REFERENCES OPERARIO_ENTREGAS(TIP_OPERARIOENTREGAS)
);

CREATE TABLE JARDINERAS (
  N_MATRICULA VARCHAR2(20) PRIMARY KEY,
  ITV DATE,
  MODELO VARCHAR2(50)
);


CREATE TABLE AVION (
  MATRICULA VARCHAR2(50) NOT NULL,
  PARKING VARCHAR2(50),
  N_PASAJEROS NUMBER,
  TIPO VARCHAR2(50),
  DAÑO VARCHAR2(100),
  CONSTRAINT PK_AVION PRIMARY KEY (MATRICULA)
);



CREATE TABLE HACER_ESCALA (
  TIP_GRUPO NUMBER NOT NULL,
  MATRICULA_AVION VARCHAR2(50) NOT NULL,
  CONSTRAINT PK_HACER_ESCALA PRIMARY KEY (TIP_GRUPO, MATRICULA_AVION),
  CONSTRAINT FK_HACER_ESCALA_GRUPO FOREIGN KEY (TIP_GRUPO) REFERENCES GRUPO(TIP_GRUPO),
  CONSTRAINT FK_HACER_ESCALA_AVION FOREIGN KEY (MATRICULA_AVION) REFERENCES AVION(MATRICULA)
);


CREATE TABLE REMOTO (
  PARKING_JARDINERAS VARCHAR2(50),
  N_MATRICULA_JARDINERAS VARCHAR2(50)NOT NULL,
  MATRICULA_AVION VARCHAR2(50)NOT NULL,
  TIP_CONDUCTOR NUMBER NOT NULL,
  CONSTRAINT PK_REMOTO PRIMARY KEY (N_MATRICULA_JARDINERAS, MATRICULA_AVION, TIP_CONDUCTOR),
  CONSTRAINT FK_REMOTO_JARDINERAS FOREIGN KEY (N_MATRICULA_JARDINERAS) REFERENCES JARDINERAS(N_MATRICULA),
  CONSTRAINT FK_REMOTO_AVION FOREIGN KEY (MATRICULA_AVION) REFERENCES AVION(MATRICULA),
  CONSTRAINT FK_REMOTO_CONDUCTOR FOREIGN KEY (TIP_CONDUCTOR) REFERENCES CONDUCTOR_JARDINERA(TIP_CONDUCTOR)
);


CREATE TABLE HIPODROMO (
  MUELLES_ABIERTOS NUMBER NOT NULL,
  DESTINOS VARCHAR2(50),
  N_MALETAS NUMBER,
  N_MUELLES NUMBER,
  CONSTRAINT PK_HIPODROMO PRIMARY KEY (MUELLES_ABIERTOS)
);


CREATE TABLE TRANSPORTAR_MALETAS (
  MUELLES_ABIERTOS NUMBER NOT NULL,
  TIP_CARRETERO NUMBER NOT NULL,
  CONSTRAINT PK_TRANSPORTAR_MALETAS PRIMARY KEY (MUELLES_ABIERTOS, TIP_CARRETERO),
  CONSTRAINT FK_TRANSPORTAR_MALETAS_HIPODROMO FOREIGN KEY (MUELLES_ABIERTOS) REFERENCES HIPODROMO (MUELLES_ABIERTOS),
  CONSTRAINT FK_TRANSPORTAR_MALETAS_CARRETERO FOREIGN KEY (TIP_CARRETERO) REFERENCES CARRETERO (TIP_CARRETERO)
);




CREATE TABLE FACTURAR (
  MUELLES_ABIERTOS NUMBER NOT NULL,
  BN VARCHAR2(20) NOT NULL,
  TIP_OPERARIOHIPODROMO NUMBER NOT NULL,
  VUELO VARCHAR2(20),
  TIP_CAPATAZHIPODROMO NUMBER NOT NULL,
  CONSTRAINT PK_FACTURAR PRIMARY KEY (BN, TIP_OPERARIOHIPODROMO, MUELLES_ABIERTOS),
  CONSTRAINT FK_FACTURAR_EQUIPAJES FOREIGN KEY (BN) REFERENCES EQUIPAJES(BN),
  CONSTRAINT FK_FACTURAR_OPERARIOS_HIPODROMO FOREIGN KEY (TIP_OPERARIOHIPODROMO, TIP_CAPATAZHIPODROMO) REFERENCES OPERARIOS_HIPODROMO(TIP_OPERARIOHIPODROMO, TIP_CAPATAZHIPODROMO),
  CONSTRAINT FK_FACTURAR_HIPODROMO FOREIGN KEY (MUELLES_ABIERTOS) REFERENCES HIPODROMO(MUELLES_ABIERTOS)
);



-----------------------BORRADO-------------------------
                                                
                                                
--DROP TABLE TRANSPORTAR_MALETAS;               
--DROP TABLE REMOTO;                            
--DROP TABLE HACER_ESCALA;                     
--DROP TABLE AVION;
--DROP TABLE JARDINERAS;
--DROP TABLE ENTREGAR;
--DROP TABLE CARRETERO;
--DROP TABLE CONDUCTOR_JARDINERA;
--DROP TABLE COORDINAR_OPERARIOS_ENTREGAS;
--DROP TABLE EQUIPAJE_ESPECIAL;
--DROP TABLE OPERARIO_ENTREGAS;
--DROP TABLE FACTURAR;
--DROP TABLE OPERARIOS_HIPODROMO;
--DROP TABLE ABRIR;
--DROP TABLE INCIDENCIAS;
--DROP TABLE OPERARIO_PISTA;
--DROP TABLE HIPODROMO;
--DROP TABLE EQUIPAJES;
--DROP TABLE CAPATAZ_HIPODROMO;
--DROP TABLE GRUPO;
--DROP TABLE CAPATAZ_PISTA;
--DROP TABLE CAPATACES;
--DROP TABLE OPERARIOS;
--DROP TABLE PERSONAL;
--DROP TABLE JEFE_DE_TURNO;
