     ------INTRODUCCION DE DATOS EN LAS TABLAS-------
                      
                      
-- JEFE_DE_TURNO
INSERT INTO JEFE_DE_TURNO (DNI, CUANTOS, ANTIGUEDAD)
SELECT '123456789A', 5, 3 FROM DUAL
UNION ALL
SELECT '234567890B', 2, 1 FROM DUAL
UNION ALL
SELECT '345678901C', 8, 5 FROM DUAL
UNION ALL
SELECT '456789012D', 10, 2 FROM DUAL
UNION ALL
SELECT '567890123E', 3, 4 FROM DUAL;





-- PERSONAL
INSERT INTO PERSONAL (TIP_PERSONAL, PCP, NOMBRE, APELLIDO, DNI_JEFE_DE_TURNO)
SELECT 1111, '1111', 'Juan', 'Pérez', '123456789A' FROM DUAL
UNION ALL
SELECT 2222, '2222', 'María', 'Gómez', '234567890B' FROM DUAL
UNION ALL
SELECT 3333, '3333', 'Pedro', 'Fernández', '345678901C' FROM DUAL
UNION ALL
SELECT 4444, '4444', 'Laura', 'Sánchez', '456789012D' FROM DUAL
UNION ALL
SELECT 5555, '5555', 'Carlos', 'González', '567890123E' FROM DUAL;





-- CAPATACES
INSERT INTO CAPATACES (DNI_CAPATAZ, TIP_CAPATAZ)
SELECT '111111111A', 1111 FROM DUAL
UNION ALL
SELECT '222222222B', 2222 FROM DUAL
UNION ALL
SELECT '333333333C', 3333 FROM DUAL
UNION ALL
SELECT '444444444D', 4444 FROM DUAL
UNION ALL
SELECT '555555555E', 5555 FROM DUAL;



-- INCIDENCIAS
INSERT INTO INCIDENCIAS (N_EXPEDIENTE, N_INCIDENCIA)
SELECT 'EXP001', 1 FROM DUAL
UNION ALL
SELECT 'EXP002', 2 FROM DUAL
UNION ALL
SELECT 'EXP003', 3 FROM DUAL
UNION ALL
SELECT 'EXP004', 4 FROM DUAL
UNION ALL
SELECT 'EXP005', 5 FROM DUAL;






INSERT INTO ABRIR (HORA, DANOS, NOM_RESP, QUIEN, TIP_PERSONAL, N_INCIDENCIA)
SELECT '10:30', 'Daño en la puerta de un vehiculo', 'Juan Pérez', 'Encargado de mantenimiento', 1111, 1 FROM DUAL
UNION ALL
SELECT '11:00', 'Fuga de agua en el baño del avion', 'María Gómez', 'Encargada de limpieza', 2222, 2 FROM DUAL
UNION ALL
SELECT '12:15', 'Problemas con el sistema eléctrico en las cintas', 'Pedro Fernández', 'Electricista', 3333, 3 FROM DUAL
UNION ALL
SELECT '14:00', 'Rotura de cristal en la ventana en la sala de descanso', 'Laura Sánchez', 'Carpintero', 4444, 4 FROM DUAL
UNION ALL
SELECT '15:45', 'Pintura descascarada en las paredes', 'Carlos González', 'Pintor', 5555, 5 FROM DUAL;



INSERT INTO CAPATAZ_PISTA (TIP_CAPATAZPISTA, EMISORA, FURGONETA, TIPO_FURGO)
SELECT 5555, 'Emisora 1', 'Furgoneta 1', 'Tipo 1' FROM DUAL
UNION ALL
SELECT 2222, 'Emisora 2', 'Furgoneta 2', 'Tipo 2' FROM DUAL
UNION ALL
SELECT 3333, 'Emisora 3', 'Furgoneta 3', 'Tipo 3' FROM DUAL
UNION ALL
SELECT 4444, 'Emisora 4', 'Furgoneta 4', 'Tipo 4' FROM DUAL
UNION ALL
SELECT 1111, 'Emisora 5', 'Furgoneta 5', 'Tipo 5' FROM DUAL;





INSERT ALL
INTO OPERARIOS (TIP_PERSONAL, CONTRATO) VALUES (1111, 'Indefinido')
INTO OPERARIOS (TIP_PERSONAL, CONTRATO) VALUES (2222, 'Temporal')
INTO OPERARIOS (TIP_PERSONAL, CONTRATO) VALUES (3333, 'Indefinido')
INTO OPERARIOS (TIP_PERSONAL, CONTRATO) VALUES (4444, 'Temporal')
INTO OPERARIOS (TIP_PERSONAL, CONTRATO) VALUES (5555, 'Temporal')
SELECT * FROM DUAL;




INSERT INTO CAPATAZ_HIPODROMO (TURNO, TIP_CAPATAZHIPODROMO)
SELECT 'Mañana', 1111 FROM DUAL
UNION ALL
SELECT 'Noche', 2222 FROM DUAL
UNION ALL
SELECT 'Tarde', 3333 FROM DUAL
UNION ALL
SELECT 'Partido', 4444 FROM DUAL
UNION ALL
SELECT 'Noche', 5555 FROM DUAL;

INSERT INTO OPERARIOS_HIPODROMO (PAUSA, DESTINOS_SALIDA, TIP_OPERARIOHIPODROMO, TIP_CAPATAZHIPODROMO)
SELECT '30 minutos', 'lba', 1111, 4444 FROM DUAL
UNION ALL
SELECT '15 minutos', 'stn', 2222, 1111 FROM DUAL
UNION ALL
SELECT '20 minutos', 'lgw', 3333, 2222 FROM DUAL
UNION ALL
SELECT '10 minutos', 'jfk', 4444, 5555 FROM DUAL
UNION ALL
SELECT '30 minutos', 'orl', 5555, 3333 FROM DUAL;




INSERT INTO GRUPO (CUANTOS, VUELOS, TIP_GRUPO, TIP_CAPATAZPISTA)
VALUES (10, 'Vuelo 1', 1111, 5555);

INSERT INTO GRUPO (CUANTOS, VUELOS, TIP_GRUPO, TIP_CAPATAZPISTA)
VALUES (15, 'Vuelo 2', 2222, 3333);

INSERT INTO GRUPO (CUANTOS, VUELOS, TIP_GRUPO, TIP_CAPATAZPISTA)
VALUES (8, 'Vuelo 3', 3333, 4444);

INSERT INTO GRUPO (CUANTOS, VUELOS, TIP_GRUPO, TIP_CAPATAZPISTA)
VALUES (12, 'Vuelo 4', 4444, 2222);

INSERT INTO GRUPO (CUANTOS, VUELOS, TIP_GRUPO, TIP_CAPATAZPISTA)
VALUES (20, 'Vuelo 5', 5555, 1111);



INSERT INTO OPERARIO_PISTA (N_BODEGAS, CINTA, MATRICULAS, TIP_GRUPOPISTA)
VALUES (5, 'Cinta 1', 'ABC123, DEF456, GHI789', 1111);

INSERT INTO OPERARIO_PISTA (N_BODEGAS, CINTA, MATRICULAS, TIP_GRUPOPISTA)
VALUES (3, 'Cinta 2', 'JKL012, MNO345, PQR678', 2222);

INSERT INTO OPERARIO_PISTA (N_BODEGAS, CINTA, MATRICULAS, TIP_GRUPOPISTA)
VALUES (4, 'Cinta 3', 'STU901, VWX234, YZ567', 3333);

INSERT INTO OPERARIO_PISTA (N_BODEGAS, CINTA, MATRICULAS, TIP_GRUPOPISTA)
VALUES (6, 'Cinta 4', 'ABC987, DEF654, GHI321', 4444);

INSERT INTO OPERARIO_PISTA (N_BODEGAS, CINTA, MATRICULAS, TIP_GRUPOPISTA)
VALUES (7, 'tractor 5', 'JKL098, MNO765, PQR432', 5555);




INSERT INTO OPERARIO_ENTREGAS (N_TRACTOR, TURNO, PAUSA, MATRICULA, TIP_OPERARIOENTREGAS)
VALUES ('Tractor 1', 'Mañana', 'Sí', 'ABC123', 1111);

INSERT INTO OPERARIO_ENTREGAS (N_TRACTOR, TURNO, PAUSA, MATRICULA, TIP_OPERARIOENTREGAS)
VALUES ('Tractor 2', 'Noche', 'No', 'DEF456', 2222);

INSERT INTO OPERARIO_ENTREGAS (N_TRACTOR, TURNO, PAUSA, MATRICULA, TIP_OPERARIOENTREGAS)
VALUES ('Tractor 3', 'Mañana', 'Sí', 'GHI789', 3333);

INSERT INTO OPERARIO_ENTREGAS (N_TRACTOR, TURNO, PAUSA, MATRICULA, TIP_OPERARIOENTREGAS)
VALUES ('Tractor 4', 'Noche', 'No', 'JKL012', 4444);

INSERT INTO OPERARIO_ENTREGAS (N_TRACTOR, TURNO, PAUSA, MATRICULA, TIP_OPERARIOENTREGAS)
VALUES ('Tractor 5', 'Mañana', 'Sí', 'MNO345', 5555);


INSERT INTO EQUIPAJES (PESO, BN, NOMBRE, TOTAL)
VALUES (15, 'BN-001', 'Juan Pérez', 1);

INSERT INTO EQUIPAJES (PESO, BN, NOMBRE, TOTAL)
VALUES (20, 'BN-002', 'Pablo Garramone', 2);

INSERT INTO EQUIPAJES (PESO, BN, NOMBRE, TOTAL)
VALUES (10, 'BN-003', 'Pedro Rodríguez', 1);

INSERT INTO EQUIPAJES (PESO, BN, NOMBRE, TOTAL)
VALUES (18, 'BN-004', 'Laura López', 3);

INSERT INTO EQUIPAJES (PESO, BN, NOMBRE, TOTAL)
VALUES (12, 'BN-005', 'Jorge García', 2);


INSERT INTO EQUIPAJE_ESPECIAL (TAMAÑO, CONTENIDO, PESO, BN)
VALUES ('Grande', 'Instrumentos musicales', 25, 'BN-001');

INSERT INTO EQUIPAJE_ESPECIAL (TAMAÑO, CONTENIDO, PESO, BN)
VALUES ('Pequeño', 'Examenes de base de datos', 5, 'BN-002');

INSERT INTO EQUIPAJE_ESPECIAL (TAMAÑO, CONTENIDO, PESO, BN)
VALUES ('Mediano', 'Equipo deportivo', 15, 'BN-003');

INSERT INTO EQUIPAJE_ESPECIAL (TAMAÑO, CONTENIDO, PESO, BN)
VALUES ('Grande', 'Equipo fotográfico', 30, 'BN-004');

-----------------------BORRADO-------------------------
                                                
                                                
--DROP TABLE TRANSPORTAR_MALETAS;               
--DROP TABLE REMOTO;                            
--DROP TABLE HACER_ESCALA;                     
--DROP TABLE AVION;
--DROP TABLE JARDINERAS;
--DROP TABLE ENTREGAR;
--DROP TABLE CARRETERO;
--DROP TABLE CONDUCTOR_JARDINERA;
--DROP TABLE COORDINAR_OPERARIOS_ENTREGAS;
--DROP TABLE EQUIPAJE_ESPECIAL;
--DROP TABLE OPERARIO_ENTREGAS;
--DROP TABLE FACTURAR;
--DROP TABLE OPERARIOS_HIPODROMO;
--DROP TABLE ABRIR;
--DROP TABLE INCIDENCIAS;
--DROP TABLE OPERARIO_PISTA;
--DROP TABLE HIPODROMO;
--DROP TABLE EQUIPAJES;
--DROP TABLE CAPATAZ_HIPODROMO;
--DROP TABLE GRUPO;
--DROP TABLE CAPATAZ_PISTA;
--DROP TABLE CAPATACES;
--DROP TABLE OPERARIOS;
--DROP TABLE PERSONAL;
--DROP TABLE JEFE_DE_TURNO;

-------------------------------------------------------
